name: Automation Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  ui-chrome-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test
        uses: actions/checkout@v2
        if: github.event.schedule == '30 13 * * 3'
        with:
          # Run regression test suite
          command: echo running
  ui-chrome-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity Test
        uses: actions/checkout@v2
        if: github.event.schedule != '30 13 * * 3'
        with:
          # Run sanity test suite
          command: echo running